on:
 workflow_dispatch:
jobs:
  buildLinuxApp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: |
         cd ..
         npm install
      - name: Build for Linux
        run: npm run make -- --platform=linux
